FROM node:lts-alpine as build-stage
WORKDIR /app
COPY ./project/package*.json ./
RUN npm install
COPY ./project .
RUN npm run build

FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY ./project/nginx.conf /etc/nginx/conf.d

CMD ["nginx", "-g", "daemon off;"]