version: '3.9'
services:

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: productmanagerproject_backend_dev
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/project/:/usr/src/project/
    ports:
      - "8000:8000"
    env_file:
      - .env_public/dev/.env.backend
    depends_on:
      - backend_db

  backend_db:
    image: postgres:13-alpine
    container_name: productmanagerproject_backend_db_dev
    volumes:
      - backend_postgres_data:/var/lib/postgresql/data/
    ports:
      - "50001:5432"
    env_file:
      - .env_public/dev/.env.db

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: productmanagerproject_frontend_dev
    command: "npm run serve"
    volumes:
      - ./frontend/project/:/usr/src/project/
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  backend_postgres_data:
