version: '3.9'
services:
  backend:
    build: ./backend
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend/project/:/usr/src/project/
    ports:
      - "8000:8000"
    env_file:
      - .env.backend.dev
    depends_on:
      - backend_db
      - cache
  backend_db:
    image: postgres:13-alpine
    volumes:
      - backend_postgres_data:/var/lib/postgresql/data/
    ports:
      - "50001:5432"
    env_file:
      - .env.db.dev
  cache:
    image: memcached:alpine
    command:
      - '--memory-limit=1024'
volumes:
  backend_postgres_data:
