FROM python:3.8-slim

WORKDIR /usr/src/project

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

COPY ./requirements/prod.txt ./requirements.txt
COPY ./project .

RUN pip install --upgrade pip --no-cache && \
    pip install -r requirements.txt --no-cache

# copy entrypoint.sh
RUN sed -i 's/\r$//g' ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["sh", "./entrypoint.sh"]
