# Generated by Django 3.2.7 on 2021-09-11 13:25

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'default_related_name': 'products', 'ordering': ['id'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productstate',
            options={'default_related_name': 'product_states', 'ordering': ['id'], 'verbose_name': 'Статус товара', 'verbose_name_plural': 'Статус товаров'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'default_related_name': 'shops', 'ordering': ['id'], 'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Максимальный допустимый уровень вложенности категории - 3', limit_choices_to=models.Q(('level__lte', 1)), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Продукты можно добавлять только в категории, которые не имеют под категорий', limit_choices_to=models.Q(('children__isnull', True)), on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.category'),
        ),
        migrations.AlterField(
            model_name='productstate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_states', to='product.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productstate',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_states_shop', to='product.shop', verbose_name='Магазин'),
        ),
        migrations.AlterUniqueTogether(
            name='productstate',
            unique_together={('product', 'shop')},
        ),
    ]
